{% set name = "Simon" %}
{% set version = "0.0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://test.pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1bb2048d40e69bd2a329a281787bf218b54ab0716e9c9d75d0411159d0b3efef

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.19.1
    - pandas >=1.1.3
    - pip
    - python
    - scanpy >=1.6.0
    - scikit-learn >=0.23.2
  run:
    - numpy >=1.19.1
    - pandas >=1.1.3
    - python
    - scanpy >=1.6.0
    - scikit-learn >=0.23.2

about:
  home: "https://github.com/SimonDMurray/test-github-actions/"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Test GitHub Actions"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
