name: publish pypi

on:
  release:
    types:
      - created

jobs:
  publish-pypi:

    runs-on: ubuntu-latest

    steps:
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
